### PR TITLE
Fix crash & Fix arithmetic overflow fixes

### PR DESCRIPTION
**Pull request by disarray2077**
Helllo again! This PR fixes 2 bugs I found since https://github.com/StbBeef/StbImageBeef/pull/2:
- Some JPEG images were wrongly green-shaded.
_Turns out this was caused by the arithmetic fixes made in https://github.com/StbBeef/StbImageBeef/pull/1, they were wrong..._
- Apparently, attempting to load any GIF used to cause a crash.

### CODE REVIEW

**Comment by rds1983** [comment]
Thanks once again!

**Comment by rds1983** [comment]
btw, are you aware of this project https://github.com/EinScott/stb_beef ?

**Comment by disarray2077** [comment]
> btw, are you aware of this project https://github.com/EinScott/stb_beef ?

Yes, although I see no point in switching to it since this one is working perfectly for my needs, and the issues in it were very simple to solve so far :)

**Comment by rds1983** [comment]
I see, makes sense.
Did you by any chance try stb_truetype from that project?

**Comment by disarray2077** [comment]
@rds1983 Sorry for the late reply- No. I use https://github.com/disarray2077/BeefFNT (BMFont) for my fonts.

**Pull request merged**
